version: "3"
services:
  web:
    # image: shoyatoa/dev_myprofile_flont:latest
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    #ホットリロードを可能にする設定
    environment:
      - WATCHPACK_POLLING=true
    entrypoint: ["sh", "-c", "npm install && npm run dev"]
