import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeaderNav from "./components/header";
import "./globals.css";
import "animate.css";

const inter = Inter({ subsets: ["latin"] });

const navgroup = [
  { label: "PROFILE", url: "" },
  { label: "WORK", url: "" },
  { label: "CONTACT", url: "" },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderNav datas={navgroup} />
        {/* <div className="header animate__animated animate__fadeInDown animate__slower">
          <nav>
            <ul>
              <li>PROFILE</li>
              <li>WORK</li>
              <li>CONTACT</li>
            </ul>
          </nav>
        </div> */}
        {children}
      </body>
    </html>
  );
}
