import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeaderNav from "./components/header";
import "./globals.css";
import "animate.css";
import FooterNav from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

const title = "OTA SHOYA";

const navgroup = [
  { label: "PROFILE", url: "" },
  { label: "WORK", url: "" },
  { label: "CONTACT", url: "" },
];

export const metadata: Metadata = {
  title: title,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderNav datas={navgroup} />
        {children}
        <FooterNav datas={navgroup} title={title} />
      </body>
    </html>
  );
}
